import { ORPCError } from "@orpc/server";
import { z } from "zod/v3";
import { generateText } from "ai";
import { pub, adminAuthed } from "@/lib/orpc/base";
import { createAdminTelegramClient } from "@/lib/sdks/admin-telegram-bot-client";
import { getRAGContext } from "@/lib/ai/get-rag-context";
import { primaryChatModel } from "@/lib/ai/models";
import { TelegramUpdateSchema } from "../telegram/telegram-schemas";
import ENVConfig from "@/config";
import { withVercelBypass } from "@/lib/utils/vercel";

function parseExportCommand(text: string): { question: string } | null {
  const match = text.match(/^@html\s+([\s\S]+)/i);
  if (!match) return null;
  return { question: match[1].trim() };
}

const HELP_MESSAGE = `\
<b>Responsibly Admin Bot</b>

Ask me anything about the platform and I'll answer using the knowledge base.

<b>Commands</b>
/help — show this message

<b>Export modifiers</b>
<code>@html</code> <i>your question</i> — answer as an HTML file

<b>Examples</b>
<code>How many active users do we have?</code>
<code>@html Summarise last month's signups</code>`;

const ALLOWED_STATUSES = new Set(["creator", "administrator", "member"]);

async function isGroupMember(botClient: ReturnType<typeof createAdminTelegramClient>, userId: number): Promise<boolean> {
  const groupId = process.env.ADMIN_TG_ALLOWED_GROUP_ID;
  // No group configured → open to everyone (useful during development)
  if (!groupId) return true;
  const status = await botClient.getChatMember(groupId, userId);
  return status !== null && ALLOWED_STATUSES.has(status);
}

function buildHtmlExportSystemPrompt(contextBlock: string): string {
  const parts = [
    `You are an admin assistant for the Responsibly platform that produces beautiful HTML reports.

Your response MUST be a single, complete, valid HTML document — nothing else. No explanation, no preamble, no markdown fences. Start with <!DOCTYPE html> and end with </html>.

Rules:
- Only answer using information from the provided knowledge base context or well-established factual knowledge.
- If the answer cannot be determined from the available information, say so clearly inside the document.
- Do not make up facts, policies, features, or data.
- The document must be self-contained: embed all CSS in a <style> tag, no external resources.

Document structure:
- <head> with charset UTF-8, viewport meta, a descriptive <title>, and a <style> block.
- <body> with a <header> containing the report title and a subtitle showing the generation timestamp.
- A <main> section holding the answer content.
- A <footer> with "Generated by Responsibly Admin Bot".

CSS requirements — produce a polished, readable document:
- Font stack: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif for body; 'SF Mono', Menlo, Consolas, monospace for code.
- Color palette: white background (#ffffff), near-black text (#111827), accent blue (#2563eb), light grey borders (#e5e7eb), subtle surface (#f9fafb).
- Max content width 860px, centered with auto horizontal margins, 48px vertical padding.
- Header: accent-coloured left border (4px solid #2563eb), padding 24px, background #f0f5ff, border-radius 8px, margin-bottom 32px.
- Headings: clear hierarchy (h1 2rem, h2 1.5rem, h3 1.2rem), font-weight 700, margin-top 2em.
- Paragraphs: line-height 1.75, margin-bottom 1em, color #374151.
- Tables: full width, border-collapse collapse; th cells have background #f3f4f6, font-weight 600, text-align left, padding 10px 14px; td cells padding 10px 14px, border-bottom 1px solid #e5e7eb; tbody tr:hover background #f9fafb.
- Lists: margin-left 1.5em, line-height 1.8.
- Code/pre: background #1e293b, color #e2e8f0, border-radius 6px; inline code padding 2px 6px; pre padding 16px, overflow-x auto, font-size 0.875em.
- Blockquote: left border 4px solid #2563eb, margin 0, padding 12px 20px, background #f0f5ff, border-radius 0 6px 6px 0, color #1e40af.
- Callout/note boxes: use <div class="callout"> — background #fffbeb, border-left 4px solid #f59e0b, padding 12px 16px, border-radius 0 6px 6px 0.
- Badges/tags: inline-block, background #dbeafe, color #1d4ed8, border-radius 9999px, padding 2px 10px, font-size 0.8em.
- Footer: margin-top 48px, padding-top 16px, border-top 1px solid #e5e7eb, font-size 0.85em, color #9ca3af, text-align right.
- Print media query: hide footer, ensure tables don't break across pages (page-break-inside avoid on tr).

Content formatting:
- Use appropriate HTML elements: <table> for tabular data, <ul>/<ol> for lists, <pre><code> for code, <blockquote> for quotes.
- Use <strong> and <em> for emphasis.
- Use <div class="callout"> for important notices or warnings.
- Use heading hierarchy to organise long answers.
- Emit clean, indented HTML.`,
  ];

  if (contextBlock) {
    parts.push(`Use the following knowledge base context to inform your answer:\n\n${contextBlock}`);
  }

  const now = new Date();
  parts.push(`Current date/time: ${now.toUTCString()}`);

  return parts.join("\n\n");
}

function buildAdminSystemPrompt(contextBlock: string): string {
  const parts = [
    `You are an admin assistant for the Responsibly platform.

Answer questions concisely and accurately.

Rules:
- Only answer using information from the provided knowledge base context or well-established factual knowledge.
- If the answer cannot be determined from the available information, say so clearly.
- Do not make up facts, policies, features, or data.
- Keep responses concise and optimized for reading on mobile devices.
- Use short paragraphs and bullet points when helpful.
- Put the most important information first.

Formatting:
- Use proper emojis when helpful.
- Return valid Telegram HTML.
- Do not use Markdown.
- Use <b>bold</b> for important points.
- Use <code>inline code</code> for commands, IDs, and technical terms.
- Use bullet points when helpful.
- Keep responses mobile-friendly with short paragraphs.
- Only use Telegram-supported HTML tags and ensure tags are properly closed.

If the user asks for something outside your knowledge, respond:
"I don't have enough information to answer that."
`,
  ];

  if (contextBlock) {
    parts.push(
      `Use the following knowledge base context to inform your answer:\n\n${contextBlock}`
    );
  }

  const now = new Date();
  parts.push(`Current date/time: ${now.toUTCString()}`);

  return parts.join("\n\n");
}

export const adminTelegramRouter = {
  setWebhook: adminAuthed
    .route({
      method: "POST",
      path: "/admin-telegram/set-webhook",
      summary: "Register the admin Telegram bot webhook (admin only)",
      tags: ["Admin Telegram"],
    })
    .input(
      z.object({
        baseUrl: z.preprocess(
          (v) => (!v ? undefined : v),
          z.string().url().optional()
        ),
      })
    )
    .output(
      z.object({
        ok: z.boolean(),
        description: z.string().optional(),
        webhookUrl: z.string(),
      })
    )
    .handler(async ({ input }) => {
      const bot = createAdminTelegramClient();
      const base = input.baseUrl ?? ENVConfig.backend_base_url;
      const webhookUrl = withVercelBypass(
        `${base}/api/v1/rest/admin-telegram/webhook`
      );
      const secret = process.env.TELEGRAM_WEBHOOK_SECRET;
      const result = await bot.setWebhook(webhookUrl, secret);
      return { ok: result.ok, description: result.description, webhookUrl };
    }),

  webhook: pub
    .route({
      method: "POST",
      path: "/admin-telegram/webhook",
      summary: "Receive admin Telegram bot updates",
      tags: ["Admin Telegram"],
    })
    .input(TelegramUpdateSchema)
    .output(z.object({ ok: z.boolean() }))
    .handler(async ({ input, context }) => {
      const secret = process.env.TELEGRAM_WEBHOOK_SECRET;
      if (secret) {
        const header = context.headers.get("x-telegram-bot-api-secret-token");
        if (header !== secret) throw new ORPCError("UNAUTHORIZED");
      }

      const bot = createAdminTelegramClient();
      const from = input.message?.from;
      const text = input.message?.text?.trim();

      console.log("[AdminBot] webhook received", { from: from?.id, text });

      if (!from || !text) return { ok: true };

      if (text === "/help") {
        try {
          await bot.sendMessage(from.id, HELP_MESSAGE, { parse_mode: "HTML" });
        } catch (err) {
          console.error("[AdminBot] failed to send help message:", err);
        }
        return { ok: true };
      }

      // Ignore all other slash commands
      if (text.startsWith("/")) return { ok: true };

      const exportCmd = parseExportCommand(text);

      const allowed = await isGroupMember(bot, from.id);
      if (!allowed) {
        try {
          await bot.sendMessage(
            from.id,
            "Access denied. You must be a member of the authorised group to use this bot."
          );
        } catch (err) {
          console.error("[AdminBot] failed to send access-denied message:", err);
        }
        return { ok: true };
      }

      const question = exportCmd?.question ?? text;
      const { context: ragContext } = await getRAGContext(question);
      const systemPrompt = exportCmd
        ? buildHtmlExportSystemPrompt(ragContext)
        : buildAdminSystemPrompt(ragContext);

      let answer: string;
      try {
        const result = await generateText({
          model: primaryChatModel,
          system: systemPrompt,
          prompt: question,
        });
        answer = result.text || "I couldn't generate a response. Please try again.";
      } catch (err) {
        console.error("[AdminBot] LLM error:", err);
        answer = "Something went wrong while generating a response. Please try again.";
      }

      if (exportCmd) {
        try {
          const file = {
            name: "response.html",
            buffer: Buffer.from(answer, "utf-8"),
            mimeType: "text/html",
          };
          await bot.sendDocument(from.id, file);
        } catch (err) {
          console.error("[AdminBot] failed to send document:", err);
          try {
            await bot.sendMessage(from.id, "Failed to generate the file. Please try again.");
          } catch { /* ignore */ }
        }
      } else {
        try {
          await bot.sendMessage(from.id, answer, { parse_mode: "HTML" });
        } catch (err) {
          console.error("[AdminBot] failed to send reply:", err);
        }
      }

      return { ok: true };
    }),
};
