/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dashboard API
 * Internal API for the personal dashboard application.
 * OpenAPI spec version: 1.0.0
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
  ZoomMeetingsCreate200,
  ZoomMeetingsCreateBody,
  ZoomMeetingsDeleteBody,
  ZoomMeetingsGet200,
  ZoomMeetingsList200,
  ZoomMeetingsListParams,
  ZoomMeetingsUpdateBody,
} from "../../model";

import { customInstance } from "@/lib/orval-clients/orval-client-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List meetings
 */
export type zoomMeetingsListResponse200 = {
  data: ZoomMeetingsList200;
  status: 200;
};

export type zoomMeetingsListResponseSuccess = zoomMeetingsListResponse200 & {
  headers: Headers;
};
export type zoomMeetingsListResponse = zoomMeetingsListResponseSuccess;

export const getZoomMeetingsListUrl = (params?: ZoomMeetingsListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `https://3144-2001-569-7bfc-3a00-f1f4-1327-a19e-63c9.ngrok-free.app/api/v1/rest/zoom/meetings?${stringifiedParams}`
    : `https://3144-2001-569-7bfc-3a00-f1f4-1327-a19e-63c9.ngrok-free.app/api/v1/rest/zoom/meetings`;
};

export const zoomMeetingsList = async (
  params?: ZoomMeetingsListParams,
  options?: RequestInit,
): Promise<zoomMeetingsListResponse> => {
  return customInstance<zoomMeetingsListResponse>(
    getZoomMeetingsListUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getZoomMeetingsListQueryKey = (
  params?: ZoomMeetingsListParams,
) => {
  return [
    `https://3144-2001-569-7bfc-3a00-f1f4-1327-a19e-63c9.ngrok-free.app/api/v1/rest/zoom/meetings`,
    ...(params ? [params] : []),
  ] as const;
};

export const getZoomMeetingsListQueryOptions = <
  TData = Awaited<ReturnType<typeof zoomMeetingsList>>,
  TError = unknown,
>(
  params?: ZoomMeetingsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof zoomMeetingsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getZoomMeetingsListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof zoomMeetingsList>>
  > = ({ signal }) => zoomMeetingsList(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof zoomMeetingsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ZoomMeetingsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof zoomMeetingsList>>
>;
export type ZoomMeetingsListQueryError = unknown;

export function useZoomMeetingsList<
  TData = Awaited<ReturnType<typeof zoomMeetingsList>>,
  TError = unknown,
>(
  params: undefined | ZoomMeetingsListParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof zoomMeetingsList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof zoomMeetingsList>>,
          TError,
          Awaited<ReturnType<typeof zoomMeetingsList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useZoomMeetingsList<
  TData = Awaited<ReturnType<typeof zoomMeetingsList>>,
  TError = unknown,
>(
  params?: ZoomMeetingsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof zoomMeetingsList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof zoomMeetingsList>>,
          TError,
          Awaited<ReturnType<typeof zoomMeetingsList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useZoomMeetingsList<
  TData = Awaited<ReturnType<typeof zoomMeetingsList>>,
  TError = unknown,
>(
  params?: ZoomMeetingsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof zoomMeetingsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List meetings
 */

export function useZoomMeetingsList<
  TData = Awaited<ReturnType<typeof zoomMeetingsList>>,
  TError = unknown,
>(
  params?: ZoomMeetingsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof zoomMeetingsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getZoomMeetingsListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a new meeting
 */
export type zoomMeetingsCreateResponse200 = {
  data: ZoomMeetingsCreate200;
  status: 200;
};

export type zoomMeetingsCreateResponseSuccess =
  zoomMeetingsCreateResponse200 & {
    headers: Headers;
  };
export type zoomMeetingsCreateResponse = zoomMeetingsCreateResponseSuccess;

export const getZoomMeetingsCreateUrl = () => {
  return `https://3144-2001-569-7bfc-3a00-f1f4-1327-a19e-63c9.ngrok-free.app/api/v1/rest/zoom/meetings`;
};

export const zoomMeetingsCreate = async (
  zoomMeetingsCreateBody: ZoomMeetingsCreateBody,
  options?: RequestInit,
): Promise<zoomMeetingsCreateResponse> => {
  return customInstance<zoomMeetingsCreateResponse>(
    getZoomMeetingsCreateUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(zoomMeetingsCreateBody),
    },
  );
};

export const getZoomMeetingsCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof zoomMeetingsCreate>>,
    TError,
    { data: ZoomMeetingsCreateBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof zoomMeetingsCreate>>,
  TError,
  { data: ZoomMeetingsCreateBody },
  TContext
> => {
  const mutationKey = ["zoomMeetingsCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof zoomMeetingsCreate>>,
    { data: ZoomMeetingsCreateBody }
  > = (props) => {
    const { data } = props ?? {};

    return zoomMeetingsCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ZoomMeetingsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof zoomMeetingsCreate>>
>;
export type ZoomMeetingsCreateMutationBody = ZoomMeetingsCreateBody;
export type ZoomMeetingsCreateMutationError = unknown;

/**
 * @summary Create a new meeting
 */
export const useZoomMeetingsCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof zoomMeetingsCreate>>,
      TError,
      { data: ZoomMeetingsCreateBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof zoomMeetingsCreate>>,
  TError,
  { data: ZoomMeetingsCreateBody },
  TContext
> => {
  return useMutation(
    getZoomMeetingsCreateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Get a meeting by ID
 */
export type zoomMeetingsGetResponse200 = {
  data: ZoomMeetingsGet200;
  status: 200;
};

export type zoomMeetingsGetResponseSuccess = zoomMeetingsGetResponse200 & {
  headers: Headers;
};
export type zoomMeetingsGetResponse = zoomMeetingsGetResponseSuccess;

export const getZoomMeetingsGetUrl = (meetingId: string) => {
  return `https://3144-2001-569-7bfc-3a00-f1f4-1327-a19e-63c9.ngrok-free.app/api/v1/rest/zoom/meetings/${meetingId}`;
};

export const zoomMeetingsGet = async (
  meetingId: string,
  options?: RequestInit,
): Promise<zoomMeetingsGetResponse> => {
  return customInstance<zoomMeetingsGetResponse>(
    getZoomMeetingsGetUrl(meetingId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getZoomMeetingsGetQueryKey = (meetingId: string) => {
  return [
    `https://3144-2001-569-7bfc-3a00-f1f4-1327-a19e-63c9.ngrok-free.app/api/v1/rest/zoom/meetings/${meetingId}`,
  ] as const;
};

export const getZoomMeetingsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof zoomMeetingsGet>>,
  TError = unknown,
>(
  meetingId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof zoomMeetingsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getZoomMeetingsGetQueryKey(meetingId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof zoomMeetingsGet>>> = ({
    signal,
  }) => zoomMeetingsGet(meetingId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!meetingId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof zoomMeetingsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ZoomMeetingsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof zoomMeetingsGet>>
>;
export type ZoomMeetingsGetQueryError = unknown;

export function useZoomMeetingsGet<
  TData = Awaited<ReturnType<typeof zoomMeetingsGet>>,
  TError = unknown,
>(
  meetingId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof zoomMeetingsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof zoomMeetingsGet>>,
          TError,
          Awaited<ReturnType<typeof zoomMeetingsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useZoomMeetingsGet<
  TData = Awaited<ReturnType<typeof zoomMeetingsGet>>,
  TError = unknown,
>(
  meetingId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof zoomMeetingsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof zoomMeetingsGet>>,
          TError,
          Awaited<ReturnType<typeof zoomMeetingsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useZoomMeetingsGet<
  TData = Awaited<ReturnType<typeof zoomMeetingsGet>>,
  TError = unknown,
>(
  meetingId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof zoomMeetingsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a meeting by ID
 */

export function useZoomMeetingsGet<
  TData = Awaited<ReturnType<typeof zoomMeetingsGet>>,
  TError = unknown,
>(
  meetingId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof zoomMeetingsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getZoomMeetingsGetQueryOptions(meetingId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update an existing meeting
 */
export type zoomMeetingsUpdateResponse200 = {
  data: unknown;
  status: 200;
};

export type zoomMeetingsUpdateResponseSuccess =
  zoomMeetingsUpdateResponse200 & {
    headers: Headers;
  };
export type zoomMeetingsUpdateResponse = zoomMeetingsUpdateResponseSuccess;

export const getZoomMeetingsUpdateUrl = (meetingId: string) => {
  return `https://3144-2001-569-7bfc-3a00-f1f4-1327-a19e-63c9.ngrok-free.app/api/v1/rest/zoom/meetings/${meetingId}`;
};

export const zoomMeetingsUpdate = async (
  meetingId: string,
  zoomMeetingsUpdateBody?: ZoomMeetingsUpdateBody,
  options?: RequestInit,
): Promise<zoomMeetingsUpdateResponse> => {
  return customInstance<zoomMeetingsUpdateResponse>(
    getZoomMeetingsUpdateUrl(meetingId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(zoomMeetingsUpdateBody),
    },
  );
};

export const getZoomMeetingsUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof zoomMeetingsUpdate>>,
    TError,
    { meetingId: string; data: ZoomMeetingsUpdateBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof zoomMeetingsUpdate>>,
  TError,
  { meetingId: string; data: ZoomMeetingsUpdateBody },
  TContext
> => {
  const mutationKey = ["zoomMeetingsUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof zoomMeetingsUpdate>>,
    { meetingId: string; data: ZoomMeetingsUpdateBody }
  > = (props) => {
    const { meetingId, data } = props ?? {};

    return zoomMeetingsUpdate(meetingId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ZoomMeetingsUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof zoomMeetingsUpdate>>
>;
export type ZoomMeetingsUpdateMutationBody = ZoomMeetingsUpdateBody;
export type ZoomMeetingsUpdateMutationError = unknown;

/**
 * @summary Update an existing meeting
 */
export const useZoomMeetingsUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof zoomMeetingsUpdate>>,
      TError,
      { meetingId: string; data: ZoomMeetingsUpdateBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof zoomMeetingsUpdate>>,
  TError,
  { meetingId: string; data: ZoomMeetingsUpdateBody },
  TContext
> => {
  return useMutation(
    getZoomMeetingsUpdateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Delete a meeting
 */
export type zoomMeetingsDeleteResponse200 = {
  data: unknown;
  status: 200;
};

export type zoomMeetingsDeleteResponseSuccess =
  zoomMeetingsDeleteResponse200 & {
    headers: Headers;
  };
export type zoomMeetingsDeleteResponse = zoomMeetingsDeleteResponseSuccess;

export const getZoomMeetingsDeleteUrl = (meetingId: string) => {
  return `https://3144-2001-569-7bfc-3a00-f1f4-1327-a19e-63c9.ngrok-free.app/api/v1/rest/zoom/meetings/${meetingId}`;
};

export const zoomMeetingsDelete = async (
  meetingId: string,
  zoomMeetingsDeleteBody?: ZoomMeetingsDeleteBody,
  options?: RequestInit,
): Promise<zoomMeetingsDeleteResponse> => {
  return customInstance<zoomMeetingsDeleteResponse>(
    getZoomMeetingsDeleteUrl(meetingId),
    {
      ...options,
      method: "DELETE",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(zoomMeetingsDeleteBody),
    },
  );
};

export const getZoomMeetingsDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof zoomMeetingsDelete>>,
    TError,
    { meetingId: string; data: ZoomMeetingsDeleteBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof zoomMeetingsDelete>>,
  TError,
  { meetingId: string; data: ZoomMeetingsDeleteBody },
  TContext
> => {
  const mutationKey = ["zoomMeetingsDelete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof zoomMeetingsDelete>>,
    { meetingId: string; data: ZoomMeetingsDeleteBody }
  > = (props) => {
    const { meetingId, data } = props ?? {};

    return zoomMeetingsDelete(meetingId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ZoomMeetingsDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof zoomMeetingsDelete>>
>;
export type ZoomMeetingsDeleteMutationBody = ZoomMeetingsDeleteBody;
export type ZoomMeetingsDeleteMutationError = unknown;

/**
 * @summary Delete a meeting
 */
export const useZoomMeetingsDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof zoomMeetingsDelete>>,
      TError,
      { meetingId: string; data: ZoomMeetingsDeleteBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof zoomMeetingsDelete>>,
  TError,
  { meetingId: string; data: ZoomMeetingsDeleteBody },
  TContext
> => {
  return useMutation(
    getZoomMeetingsDeleteMutationOptions(options),
    queryClient,
  );
};
