/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dashboard API
 * Internal API for the personal dashboard application.
 * OpenAPI spec version: 1.0.0
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useQuery } from "@tanstack/react-query";

import type { SessionCurrent200, SessionMe200 } from "../../model";

import { customInstance } from "../../../lib/orval-clients/orval-client-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get the current authenticated user
 */
export type sessionMeResponse200 = {
  data: SessionMe200;
  status: 200;
};

export type sessionMeResponseSuccess = sessionMeResponse200 & {
  headers: Headers;
};
export type sessionMeResponse = sessionMeResponseSuccess;

export const getSessionMeUrl = () => {
  return `https://3144-2001-569-7bfc-3a00-f1f4-1327-a19e-63c9.ngrok-free.app/api/v1/rest/session/me`;
};

export const sessionMe = async (
  options?: RequestInit,
): Promise<sessionMeResponse> => {
  return customInstance<sessionMeResponse>(getSessionMeUrl(), {
    ...options,
    method: "GET",
  });
};

export const getSessionMeQueryKey = () => {
  return [
    `https://3144-2001-569-7bfc-3a00-f1f4-1327-a19e-63c9.ngrok-free.app/api/v1/rest/session/me`,
  ] as const;
};

export const getSessionMeQueryOptions = <
  TData = Awaited<ReturnType<typeof sessionMe>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof sessionMe>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSessionMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof sessionMe>>> = ({
    signal,
  }) => sessionMe({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof sessionMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SessionMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof sessionMe>>
>;
export type SessionMeQueryError = unknown;

export function useSessionMe<
  TData = Awaited<ReturnType<typeof sessionMe>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sessionMe>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionMe>>,
          TError,
          Awaited<ReturnType<typeof sessionMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSessionMe<
  TData = Awaited<ReturnType<typeof sessionMe>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sessionMe>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionMe>>,
          TError,
          Awaited<ReturnType<typeof sessionMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSessionMe<
  TData = Awaited<ReturnType<typeof sessionMe>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sessionMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get the current authenticated user
 */

export function useSessionMe<
  TData = Awaited<ReturnType<typeof sessionMe>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sessionMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSessionMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get the current session with user
 */
export type sessionCurrentResponse200 = {
  data: SessionCurrent200;
  status: 200;
};

export type sessionCurrentResponseSuccess = sessionCurrentResponse200 & {
  headers: Headers;
};
export type sessionCurrentResponse = sessionCurrentResponseSuccess;

export const getSessionCurrentUrl = () => {
  return `https://3144-2001-569-7bfc-3a00-f1f4-1327-a19e-63c9.ngrok-free.app/api/v1/rest/session/current`;
};

export const sessionCurrent = async (
  options?: RequestInit,
): Promise<sessionCurrentResponse> => {
  return customInstance<sessionCurrentResponse>(getSessionCurrentUrl(), {
    ...options,
    method: "GET",
  });
};

export const getSessionCurrentQueryKey = () => {
  return [
    `https://3144-2001-569-7bfc-3a00-f1f4-1327-a19e-63c9.ngrok-free.app/api/v1/rest/session/current`,
  ] as const;
};

export const getSessionCurrentQueryOptions = <
  TData = Awaited<ReturnType<typeof sessionCurrent>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof sessionCurrent>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSessionCurrentQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof sessionCurrent>>> = ({
    signal,
  }) => sessionCurrent({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof sessionCurrent>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SessionCurrentQueryResult = NonNullable<
  Awaited<ReturnType<typeof sessionCurrent>>
>;
export type SessionCurrentQueryError = unknown;

export function useSessionCurrent<
  TData = Awaited<ReturnType<typeof sessionCurrent>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sessionCurrent>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionCurrent>>,
          TError,
          Awaited<ReturnType<typeof sessionCurrent>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSessionCurrent<
  TData = Awaited<ReturnType<typeof sessionCurrent>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sessionCurrent>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionCurrent>>,
          TError,
          Awaited<ReturnType<typeof sessionCurrent>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSessionCurrent<
  TData = Awaited<ReturnType<typeof sessionCurrent>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sessionCurrent>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get the current session with user
 */

export function useSessionCurrent<
  TData = Awaited<ReturnType<typeof sessionCurrent>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof sessionCurrent>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSessionCurrentQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
