/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dashboard API
 * Internal API for the personal dashboard application.
 * OpenAPI spec version: 1.0.0
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useQuery } from "@tanstack/react-query";

import type { ZoomProfile200, ZoomStatus200 } from "../../model";

import { customInstance } from "../../../lib/orval-clients/orval-client-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Check Zoom connection status
 */
export type zoomStatusResponse200 = {
  data: ZoomStatus200;
  status: 200;
};

export type zoomStatusResponseSuccess = zoomStatusResponse200 & {
  headers: Headers;
};
export type zoomStatusResponse = zoomStatusResponseSuccess;

export const getZoomStatusUrl = () => {
  return `https://3144-2001-569-7bfc-3a00-f1f4-1327-a19e-63c9.ngrok-free.app/api/v1/rest/zoom/status`;
};

export const zoomStatus = async (
  options?: RequestInit,
): Promise<zoomStatusResponse> => {
  return customInstance<zoomStatusResponse>(getZoomStatusUrl(), {
    ...options,
    method: "GET",
  });
};

export const getZoomStatusQueryKey = () => {
  return [
    `https://3144-2001-569-7bfc-3a00-f1f4-1327-a19e-63c9.ngrok-free.app/api/v1/rest/zoom/status`,
  ] as const;
};

export const getZoomStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof zoomStatus>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof zoomStatus>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getZoomStatusQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof zoomStatus>>> = ({
    signal,
  }) => zoomStatus({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof zoomStatus>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ZoomStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof zoomStatus>>
>;
export type ZoomStatusQueryError = unknown;

export function useZoomStatus<
  TData = Awaited<ReturnType<typeof zoomStatus>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof zoomStatus>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof zoomStatus>>,
          TError,
          Awaited<ReturnType<typeof zoomStatus>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useZoomStatus<
  TData = Awaited<ReturnType<typeof zoomStatus>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof zoomStatus>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof zoomStatus>>,
          TError,
          Awaited<ReturnType<typeof zoomStatus>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useZoomStatus<
  TData = Awaited<ReturnType<typeof zoomStatus>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof zoomStatus>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Check Zoom connection status
 */

export function useZoomStatus<
  TData = Awaited<ReturnType<typeof zoomStatus>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof zoomStatus>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getZoomStatusQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get authenticated Zoom user profile
 */
export type zoomProfileResponse200 = {
  data: ZoomProfile200;
  status: 200;
};

export type zoomProfileResponseSuccess = zoomProfileResponse200 & {
  headers: Headers;
};
export type zoomProfileResponse = zoomProfileResponseSuccess;

export const getZoomProfileUrl = () => {
  return `https://3144-2001-569-7bfc-3a00-f1f4-1327-a19e-63c9.ngrok-free.app/api/v1/rest/zoom/profile`;
};

export const zoomProfile = async (
  options?: RequestInit,
): Promise<zoomProfileResponse> => {
  return customInstance<zoomProfileResponse>(getZoomProfileUrl(), {
    ...options,
    method: "GET",
  });
};

export const getZoomProfileQueryKey = () => {
  return [
    `https://3144-2001-569-7bfc-3a00-f1f4-1327-a19e-63c9.ngrok-free.app/api/v1/rest/zoom/profile`,
  ] as const;
};

export const getZoomProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof zoomProfile>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof zoomProfile>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getZoomProfileQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof zoomProfile>>> = ({
    signal,
  }) => zoomProfile({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof zoomProfile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ZoomProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof zoomProfile>>
>;
export type ZoomProfileQueryError = unknown;

export function useZoomProfile<
  TData = Awaited<ReturnType<typeof zoomProfile>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof zoomProfile>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof zoomProfile>>,
          TError,
          Awaited<ReturnType<typeof zoomProfile>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useZoomProfile<
  TData = Awaited<ReturnType<typeof zoomProfile>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof zoomProfile>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof zoomProfile>>,
          TError,
          Awaited<ReturnType<typeof zoomProfile>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useZoomProfile<
  TData = Awaited<ReturnType<typeof zoomProfile>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof zoomProfile>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get authenticated Zoom user profile
 */

export function useZoomProfile<
  TData = Awaited<ReturnType<typeof zoomProfile>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof zoomProfile>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getZoomProfileQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
