/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dashboard API
 * Internal API for the personal dashboard application.
 * OpenAPI spec version: 1.0.0
 */

export type SessionMe200 = {
  id: string;
  name: string;
  email: string;
  emailVerified: boolean;
  image?: string | null;
  createdAt: string;
  updatedAt: string;
};
