/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dashboard API
 * Internal API for the personal dashboard application.
 * OpenAPI spec version: 1.0.0
 */
import type { SessionCurrent200Session } from "./sessionCurrent200Session";
import type { SessionCurrent200User } from "./sessionCurrent200User";

export type SessionCurrent200 = {
  session: SessionCurrent200Session;
  user: SessionCurrent200User;
};
