/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dashboard API
 * Internal API for the personal dashboard application.
 * OpenAPI spec version: 1.0.0
 */

export type ZoomMeetingsList200MeetingsItem = {
  id: number;
  uuid: string;
  host_id: string;
  topic: string;
  /** 1=instant, 2=scheduled, 3=recurring (no fixed time), 8=recurring (fixed time) */
  type: number;
  status?: string;
  start_time?: string;
  /** Duration in minutes */
  duration?: number;
  timezone?: string;
  created_at?: string;
  join_url?: string;
  agenda?: string;
  password?: string;
};
