/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dashboard API
 * Internal API for the personal dashboard application.
 * OpenAPI spec version: 1.0.0
 */
import type { ZoomMeetingsListType } from "./zoomMeetingsListType";

export type ZoomMeetingsListParams = {
  /**
   * Filter by meeting type
   */
  type?: ZoomMeetingsListType;
  /**
   * Number of records per page
   * @minimum 1
   * @maximum 300
   */
  page_size?: number;
  /**
   * Page number
   * @minimum 1
   */
  page_number?: number;
};
