/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dashboard API
 * Internal API for the personal dashboard application.
 * OpenAPI spec version: 1.0.0
 */

export type ZoomMeetingsListType =
  (typeof ZoomMeetingsListType)[keyof typeof ZoomMeetingsListType];

export const ZoomMeetingsListType = {
  scheduled: "scheduled",
  live: "live",
  upcoming: "upcoming",
} as const;
