/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dashboard API
 * Internal API for the personal dashboard application.
 * OpenAPI spec version: 1.0.0
 */
import type { ZoomMeetingsList200MeetingsItem } from "./zoomMeetingsList200MeetingsItem";

export type ZoomMeetingsList200 = {
  page_count: number;
  page_number: number;
  page_size: number;
  total_records: number;
  meetings: ZoomMeetingsList200MeetingsItem[];
};
