/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dashboard API
 * Internal API for the personal dashboard application.
 * OpenAPI spec version: 1.0.0
 */
import type { ZoomMeetingsCreateBodySettings } from "./zoomMeetingsCreateBodySettings";

export type ZoomMeetingsCreateBody = {
  /** Meeting topic / title */
  topic: string;
  /** 1=instant, 2=scheduled, 3=recurring (no fixed time), 8=recurring (fixed time) */
  type?: number;
  /** ISO 8601 datetime, e.g. 2026-03-20T10:00:00Z */
  start_time?: string;
  /** Duration in minutes */
  duration?: number;
  timezone?: string;
  agenda?: string;
  password?: string;
  settings?: ZoomMeetingsCreateBodySettings;
};
