/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dashboard API
 * Internal API for the personal dashboard application.
 * OpenAPI spec version: 1.0.0
 */
import type { ZoomMeetingsUpdateBodySettings } from "./zoomMeetingsUpdateBodySettings";

export type ZoomMeetingsUpdateBody = {
  topic?: string;
  type?: number;
  /** ISO 8601 datetime */
  start_time?: string;
  /** Duration in minutes */
  duration?: number;
  timezone?: string;
  agenda?: string;
  password?: string;
  settings?: ZoomMeetingsUpdateBodySettings;
};
