/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Dashboard API
 * Internal API for the personal dashboard application.
 * OpenAPI spec version: 1.0.0
 */

export type ZoomProfile200 = {
  id: string;
  first_name: string;
  last_name: string;
  email: string;
  type: number;
  role_name: string;
  pmi: number;
  use_pmi: boolean;
  personal_meeting_url: string;
  timezone: string;
  created_at: string;
  last_login_time: string;
  pic_url: string;
  status: string;
};
